// scripts/generate-sitemap.mjs
// Generates public/sitemap.xml from static routes + content collections.
// Mirrors the ordering in src/utils/compositionLoader.ts so that section-level
// URLs match the indices the app actually routes to:
//   /composition/:collection/composition/:index/section/:sectionId
// Run manually with `npm run generate-sitemap`; also runs as part of `npm run build`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ORIGIN = 'https://lawsofexistence.com';

// Static, always-valid entry points (grids, case landings, feature + legal pages).
const STATIC_ROUTES = [
  ['/', '1.0'],
  ['/composition/constitutional', '0.9'],
  ['/kirchner-v-johnson', '0.9'],
  ['/kirchner-v-ellison', '0.9'],
  ['/kirchner-v-acosta', '0.9'],
  ['/composition/manuscript', '0.8'],
  ['/composition/data', '0.8'],
  ['/composition/copyright', '0.6'],
  ['/scotus-amicus', '0.7'],
  ['/for-journalists', '0.7'],
  ['/scotus-shadow-docket', '0.7'],
  ['/constitutional-accountability', '0.7'],
  ['/timeline', '0.6'],
  ['/worldmap', '0.6'],
  ['/videos', '0.6'],
  ['/individuals-metrics', '0.5'],
  ['/contact', '0.5'],
  ['/partners', '0.4'],
  ['/donate', '0.4'],
  ['/legal-disclaimers', '0.3'],
  ['/terms-of-service', '0.3'],
  ['/privacy-policy', '0.3'],
];

// Collections whose individual sections are meaningful reading URLs.
// (`map` = world-map visualization data, `timeline` = served by /timeline — both excluded.)
const READING_COLLECTIONS = ['manuscript', 'data', 'constitutional', 'copyright'];

function loadCollection(collection) {
  const dir = join(ROOT, 'content', collection);
  let files;
  try {
    files = readdirSync(dir).filter((f) => f.endsWith('.json'));
  } catch {
    return [];
  }
  const comps = [];
  for (const file of files) {
    try {
      const data = JSON.parse(readFileSync(join(dir, file), 'utf8'));
      const title = data.title || data.name || 'Untitled';
      const hasSections = Array.isArray(data.sections) && data.sections.length > 0;
      const sectionCount = hasSections ? data.sections.length : 1;
      // compositionLoader sets composition.featured from sections[0].featured
      const featured = hasSections ? Boolean(data.sections[0].featured) : false;
      comps.push({ title, sectionCount, featured, file });
    } catch (e) {
      console.warn(`  ! skipped malformed ${collection}/${file}: ${e.message}`);
    }
  }
  // Mirror compositionLoader.ts sort (within one collection_type): featured first, then title asc.
  comps.sort((a, b) => {
    if (a.featured !== b.featured) return b.featured ? 1 : -1;
    return a.title.localeCompare(b.title);
  });
  return comps;
}

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const urls = STATIC_ROUTES.map(([loc, priority]) => ({ loc: ORIGIN + loc, priority }));

let sectionTotal = 0;
for (const collection of READING_COLLECTIONS) {
  const comps = loadCollection(collection);
  console.log(`\n${collection}: ${comps.length} composition(s)`);
  comps.forEach((comp, i) => {
    const index = i + 1;
    console.log(`  ${index}. "${comp.title}" — ${comp.sectionCount} section(s)${comp.featured ? ' [featured]' : ''}`);
    for (let s = 1; s <= comp.sectionCount; s++) {
      urls.push({ loc: `${ORIGIN}/composition/${collection}/composition/${index}/section/${s}`, priority: '0.6' });
      sectionTotal++;
    }
  });
}

const body = urls
  .map((u) => `  <url><loc>${xmlEscape(u.loc)}</loc><priority>${u.priority}</priority></url>`)
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. Run: npm run generate-sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(join(ROOT, 'public', 'sitemap.xml'), xml);
console.log(`\n✓ Wrote public/sitemap.xml — ${urls.length} URLs (${STATIC_ROUTES.length} static + ${sectionTotal} sections)`);
