// scripts/generate-sitemap.mjs
// Generates public/sitemap.xml from static routes + content collections, emitting only
// CANONICAL descriptive URLs (no positional /composition/:collection/composition/:index
// forms — those are frozen to 301s by scripts/freeze-legacy-urls.mjs).
//
//   constitutional                -> /<caseSlug>/<sectionSlug>
//   manuscript | data | copyright -> /composition/<collection>/<compositionSlug>/<sectionSlug>
//
// Slugs are read from the content data (populated by scripts/enrich-content-slugs.mjs);
// this script does NOT compute positional indices. <lastmod> per section URL comes from
// the content file's last git commit date (fallback: fs mtime), cached per file.
// Run manually with `npm run generate-sitemap`; also runs as part of `npm run build`.
import { writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { ROOT, READING_COLLECTIONS, loadCollection } from './lib/content-model.mjs';

const ORIGIN = 'https://lawsofexistence.com';

// Static, always-valid entry points (grids, case landings, feature + legal pages).
const STATIC_ROUTES = [
  ['/', '1.0'],
  ['/composition/constitutional', '0.9'],
  ['/kirchner-v-johnson', '0.9'],
  ['/kirchner-v-ellison', '0.9'],
  ['/kirchner-v-acosta', '0.9'],
  ['/composition/manuscript', '0.8'],
  ['/composition/data', '0.8'],
  ['/composition/copyright', '0.6'],
  ['/scotus-amicus', '0.7'],
  ['/for-journalists', '0.7'],
  ['/scotus-shadow-docket', '0.7'],
  ['/constitutional-accountability', '0.7'],
  ['/timeline', '0.6'],
  ['/worldmap', '0.6'],
  ['/videos', '0.6'],
  ['/individuals-metrics', '0.5'],
  ['/contact', '0.5'],
  ['/partners', '0.4'],
  ['/donate', '0.4'],
  ['/legal-disclaimers', '0.3'],
  ['/terms-of-service', '0.3'],
  ['/privacy-policy', '0.3'],
];

const xmlEscape = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Last-modified date for a content file: git commit date, fallback fs mtime. Cached.
const lastmodCache = new Map();
function lastmodFor(collection, filename) {
  const rel = `content/${collection}/${filename}`;
  if (lastmodCache.has(rel)) return lastmodCache.get(rel);
  let iso;
  try {
    const out = execSync(`git log -1 --format=%cI -- "${rel}"`, {
      cwd: ROOT,
      encoding: 'utf8',
    }).trim();
    iso = out || null;
  } catch {
    iso = null;
  }
  if (!iso) {
    try {
      iso = statSync(join(ROOT, rel)).mtime.toISOString();
    } catch {
      iso = null;
    }
  }
  lastmodCache.set(rel, iso);
  return iso;
}

const urls = STATIC_ROUTES.map(([loc, priority]) => ({ loc: ORIGIN + loc, priority }));

let sectionTotal = 0;
for (const collection of READING_COLLECTIONS) {
  const comps = loadCollection(collection);
  console.log(`\n${collection}: ${comps.length} composition(s)`);
  for (const comp of comps) {
    if (!comp.slug) throw new Error(`${collection}/${comp.filename}: missing composition slug (run enrich first)`);
    const sections = Array.isArray(comp.sections) ? comp.sections : [];
    const lastmod = lastmodFor(collection, comp.filename);
    console.log(`  ${comp.slug} — ${sections.length} section(s)`);
    for (const section of sections) {
      if (!section.slug) {
        throw new Error(`${collection}/${comp.filename}: a section is missing its slug (run enrich first)`);
      }
      const path =
        collection === 'constitutional'
          ? `/${comp.slug}/${section.slug}`
          : `/composition/${collection}/${comp.slug}/${section.slug}`;
      urls.push({ loc: ORIGIN + path, priority: '0.6', lastmod });
      sectionTotal += 1;
    }
  }
}

// Self-check: no legacy positional forms may leak into the canonical sitemap.
const positional = urls.filter((u) => /\/composition\/[a-z]+\/composition\/\d+/.test(u.loc));
if (positional.length > 0) {
  console.error(`ERROR: ${positional.length} positional URL(s) leaked into sitemap:`);
  positional.slice(0, 10).forEach((u) => console.error(`  - ${u.loc}`));
  process.exit(1);
}

const body = urls
  .map((u) => {
    const lm = u.lastmod ? `<lastmod>${u.lastmod}</lastmod>` : '';
    return `  <url><loc>${xmlEscape(u.loc)}</loc>${lm}<priority>${u.priority}</priority></url>`;
  })
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. Run: npm run generate-sitemap -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(join(ROOT, 'public', 'sitemap.xml'), xml);
console.log(`\n✓ Wrote public/sitemap.xml — ${urls.length} URLs (${STATIC_ROUTES.length} static + ${sectionTotal} sections)`);
